import api from '../api/client';

const adminService = {
  dashboard: () => api.get('/admin/dashboard'),
  getProducts: (p) => api.get('/products', { params: p }),
  createProduct: (d) => api.post('/admin/products', d),
  updateProduct: (id, d) => api.put(`/admin/products/${id}`, d),
  deleteProduct: (id) => api.delete(`/admin/products/${id}`),
  getOrders: (p) => api.get('/admin/orders', { params: p }),
  updateOrderStatus: (id, s) => api.patch(`/admin/orders/${id}/status?status=${s}`),
  getUsers: (p) => api.get('/admin/users', { params: p }),
  blockUser: (id, b) => api.patch(`/admin/users/${id}/block?blocked=${b}`),
  getBlogs: (p) => api.get('/admin/blogs', { params: p }),
  createBlog: (d) => api.post('/admin/blogs', d),
  updateBlog: (id, d) => api.put(`/admin/blogs/${id}`, d),
  deleteBlog: (id) => api.delete(`/admin/blogs/${id}`),
  getCategories: () => api.get('/admin/categories'),
  createCategory: (d) => api.post('/admin/categories', d),
  updateCategory: (id, d) => api.put(`/admin/categories/${id}`, d),
  deleteCategory: (id) => api.delete(`/admin/categories/${id}`),
  getBrands: () => api.get('/admin/brands'),
  createBrand: (d) => api.post('/admin/brands', d),
  updateBrand: (id, d) => api.put(`/admin/brands/${id}`, d),
  deleteBrand: (id) => api.delete(`/admin/brands/${id}`),
  getServices: () => api.get('/services'),
  createService: (d) => api.post('/admin/services', d),
  updateService: (id, d) => api.put(`/admin/services/${id}`, d),
  deleteService: (id) => api.delete(`/admin/services/${id}`),
  getPortfolio: (p) => api.get('/admin/portfolio', { params: p }),
  createPortfolio: (d) => api.post('/admin/portfolio', d),
  updatePortfolio: (id, d) => api.put(`/admin/portfolio/${id}`, d),
  deletePortfolio: (id) => api.delete(`/admin/portfolio/${id}`),
  getBanners: () => api.get('/admin/banners'),
  createBanner: (d) => api.post('/admin/banners', d),
  updateBanner: (id, d) => api.put(`/admin/banners/${id}`, d),
  deleteBanner: (id) => api.delete(`/admin/banners/${id}`),
  uploadFile: (file) => { const fd = new FormData(); fd.append('file', file); return api.post('/admin/upload', fd, { headers: { 'Content-Type': 'multipart/form-data' } }); },
};

export default adminService;
